export const COUNTRIES = [
  { name: "Afghanistan", code: "AF", phoneCode: "+93", phoneNumberLength: 9 },
  { name: "Åland Islands", code: "AX", phoneCode: "+358", phoneNumberLength: 9 },
  { name: "Albania", code: "AL", phoneCode: "+355", phoneNumberLength: 9 },
  { name: "Algeria", code: "DZ", phoneCode: "+213", phoneNumberLength: 9 },
  { name: "American Samoa", code: "AS", phoneCode: "+1-684", phoneNumberLength: 7 },
  { name: "AndorrA", code: "AD", phoneCode: "+376", phoneNumberLength: 6 },
  { name: "Angola", code: "AO", phoneCode: "+244", phoneNumberLength: 9 },
  { name: "Anguilla", code: "AI", phoneCode: "+1-264", phoneNumberLength: 7 },
  { name: "Antarctica", code: "AQ", phoneCode: "+672", phoneNumberLength: 6 },
  { name: "Antigua and Barbuda", code: "AG", phoneCode: "+1-268", phoneNumberLength: 7 },
  { name: "Argentina", code: "AR", phoneCode: "+54", phoneNumberLength: 10 },
  { name: "Armenia", code: "AM", phoneCode: "+374", phoneNumberLength: 8 },
  { name: "Aruba", code: "AW", phoneCode: "+297", phoneNumberLength: 7 },
  { name: "Australia", code: "AU", phoneCode: "+61", phoneNumberLength: 9 },
  { name: "Austria", code: "AT", phoneCode: "+43", phoneNumberLength: 10 },
  { name: "Azerbaijan", code: "AZ", phoneCode: "+994", phoneNumberLength: 9 },
  { name: "Bahamas", code: "BS", phoneCode: "+1-242", phoneNumberLength: 7 },
  { name: "Bahrain", code: "BH", phoneCode: "+973", phoneNumberLength: 8 },
  { name: "Bangladesh", code: "BD", phoneCode: "+880", phoneNumberLength: 10 },
  { name: "Barbados", code: "BB", phoneCode: "+1-246", phoneNumberLength: 7 },
  { name: "Belarus", code: "BY", phoneCode: "+375", phoneNumberLength: 9 },
  { name: "Belgium", code: "BE", phoneCode: "+32", phoneNumberLength: 9 },
  { name: "Belize", code: "BZ", phoneCode: "+501", phoneNumberLength: 7 },
  { name: "Benin", code: "BJ", phoneCode: "+229", phoneNumberLength: 8 },
  { name: "Bermuda", code: "BM", phoneCode: "+1-441", phoneNumberLength: 7 },
  { name: "Bhutan", code: "BT", phoneCode: "+975", phoneNumberLength: 8 },
  { name: "Bolivia", code: "BO", phoneCode: "+591", phoneNumberLength: 8 },
  { name: "Bosnia and Herzegovina", code: "BA", phoneCode: "+387", phoneNumberLength: 8 },
  { name: "Botswana", code: "BW", phoneCode: "+267", phoneNumberLength: 8 },
  { name: "Bouvet Island", code: "BV", phoneCode: "+47", phoneNumberLength: 8 },
  { name: "Brazil", code: "BR", phoneCode: "+55", phoneNumberLength: 11 },
  { name: "British Indian Ocean Territory", code: "IO", phoneCode: "+246", phoneNumberLength: 7 },
  { name: "Brunei Darussalam", code: "BN", phoneCode: "+673", phoneNumberLength: 7 },
  { name: "Bulgaria", code: "BG", phoneCode: "+359", phoneNumberLength: 9 },
  { name: "Burkina Faso", code: "BF", phoneCode: "+226", phoneNumberLength: 8 },
  { name: "Burundi", code: "BI", phoneCode: "+257", phoneNumberLength: 8 },
  { name: "Cambodia", code: "KH", phoneCode: "+855", phoneNumberLength: 8 },
  { name: "Cameroon", code: "CM", phoneCode: "+237", phoneNumberLength: 9 },
  { name: "Canada", code: "CA", phoneCode: "+1", phoneNumberLength: 10 },
  { name: "Cape Verde", code: "CV", phoneCode: "+238", phoneNumberLength: 7 },
  { name: "Cayman Islands", code: "KY", phoneCode: "+1-345", phoneNumberLength: 7 },
  { name: "Central African Republic", code: "CF", phoneCode: "+236", phoneNumberLength: 8 },
  { name: "Chad", code: "TD", phoneCode: "+235", phoneNumberLength: 8 },
  { name: "Chile", code: "CL", phoneCode: "+56", phoneNumberLength: 9 },
  { name: "China", code: "CN", phoneCode: "+86", phoneNumberLength: 11 },
  { name: "Christmas Island", code: "CX", phoneCode: "+61", phoneNumberLength: 9 },
  { name: "Cocos (Keeling) Islands", code: "CC", phoneCode: "+61", phoneNumberLength: 9 },
  { name: "Colombia", code: "CO", phoneCode: "+57", phoneNumberLength: 10 },
  { name: "Comoros", code: "KM", phoneCode: "+269", phoneNumberLength: 7 },
  { name: "Congo", code: "CG", phoneCode: "+242", phoneNumberLength: 9 },
  { name: "Congo, The Democratic Republic of the", code: "CD", phoneCode: "+243", phoneNumberLength: 9 },
  { name: "Cook Islands", code: "CK", phoneCode: "+682", phoneNumberLength: 5 },
  { name: "Costa Rica", code: "CR", phoneCode: "+506", phoneNumberLength: 8 },
  { name: "Cote D'Ivoire", code: "CI", phoneCode: "+225", phoneNumberLength: 8 },
  { name: "Croatia", code: "HR", phoneCode: "+385", phoneNumberLength: 9 },
  { name: "Cuba", code: "CU", phoneCode: "+53", phoneNumberLength: 8 },
  { name: "Cyprus", code: "CY", phoneCode: "+357", phoneNumberLength: 8 },
  { name: "Czech Republic", code: "CZ", phoneCode: "+420", phoneNumberLength: 9 },
  { name: "Denmark", code: "DK", phoneCode: "+45", phoneNumberLength: 8 },
  { name: "Djibouti", code: "DJ", phoneCode: "+253", phoneNumberLength: 8 },
  { name: "Dominica", code: "DM", phoneCode: "+1-767", phoneNumberLength: 7 },
  { name: "Dominican Republic", code: "DO", phoneCode: "+1-809", phoneNumberLength: 10 },
  { name: "Ecuador", code: "EC", phoneCode: "+593", phoneNumberLength: 9 },
  { name: "Egypt", code: "EG", phoneCode: "+20", phoneNumberLength: 10 },
  { name: "El Salvador", code: "SV", phoneCode: "+503", phoneNumberLength: 8 },
  { name: "Equatorial Guinea", code: "GQ", phoneCode: "+240", phoneNumberLength: 9 },
  { name: "Eritrea", code: "ER", phoneCode: "+291", phoneNumberLength: 7 },
  { name: "Estonia", code: "EE", phoneCode: "+372", phoneNumberLength: 8 },
  { name: "Ethiopia", code: "ET", phoneCode: "+251", phoneNumberLength: 9 },
  { name: "Falkland Islands (Malvinas)", code: "FK", phoneCode: "+500", phoneNumberLength: 5 },
  { name: "Faroe Islands", code: "FO", phoneCode: "+298", phoneNumberLength: 6 },
  { name: "Fiji", code: "FJ", phoneCode: "+679", phoneNumberLength: 7 },
  { name: "Finland", code: "FI", phoneCode: "+358", phoneNumberLength: 9 },
  { name: "France", code: "FR", phoneCode: "+33", phoneNumberLength: 9 },
  { name: "French Guiana", code: "GF", phoneCode: "+594", phoneNumberLength: 9 },
  { name: "French Polynesia", code: "PF", phoneCode: "+689", phoneNumberLength: 6 },
  { name: "French Southern Territories", code: "TF", phoneCode: "+262", phoneNumberLength: 9 },
  { name: "Gabon", code: "GA", phoneCode: "+241", phoneNumberLength: 7 },
  { name: "Gambia", code: "GM", phoneCode: "+220", phoneNumberLength: 7 },
  { name: "Georgia", code: "GE", phoneCode: "+995", phoneNumberLength: 9 },
  { name: "Germany", code: "DE", phoneCode: "+49", phoneNumberLength: 11 },
  { name: "Ghana", code: "GH", phoneCode: "+233", phoneNumberLength: 9 },
  { name: "Gibraltar", code: "GI", phoneCode: "+350", phoneNumberLength: 8 },
  { name: "Greece", code: "GR", phoneCode: "+30", phoneNumberLength: 10 },
  { name: "Greenland", code: "GL", phoneCode: "+299", phoneNumberLength: 6 },
  { name: "Grenada", code: "GD", phoneCode: "+1-473", phoneNumberLength: 7 },
  { name: "Guadeloupe", code: "GP", phoneCode: "+590", phoneNumberLength: 9 },
  { name: "Guam", code: "GU", phoneCode: "+1-671", phoneNumberLength: 7 },
  { name: "Guatemala", code: "GT", phoneCode: "+502", phoneNumberLength: 8 },
  { name: "Guernsey", code: "GG", phoneCode: "+44", phoneNumberLength: 10 },
  { name: "Guinea", code: "GN", phoneCode: "+224", phoneNumberLength: 9 },
  { name: "Guinea-Bissau", code: "GW", phoneCode: "+245", phoneNumberLength: 7 },
  { name: "Guyana", code: "GY", phoneCode: "+592", phoneNumberLength: 7 },
  { name: "Haiti", code: "HT", phoneCode: "+509", phoneNumberLength: 8 },
  { name: "Heard Island and Mcdonald Islands", code: "HM", phoneCode: "+672", phoneNumberLength: 6 },
  { name: "Holy See (Vatican City State)", code: "VA", phoneCode: "+379", phoneNumberLength: 7 },
  { name: "Honduras", code: "HN", phoneCode: "+504", phoneNumberLength: 8 },
  { name: "Hong Kong", code: "HK", phoneCode: "+852", phoneNumberLength: 8 },
  { name: "Hungary", code: "HU", phoneCode: "+36", phoneNumberLength: 9 },
  { name: "Iceland", code: "IS", phoneCode: "+354", phoneNumberLength: 7 },
  { name: "India", code: "IN", phoneCode: "+91", phoneNumberLength: 10 },
  { name: "Indonesia", code: "ID", phoneCode: "+62", phoneNumberLength: 10 },
  { name: "Iran, Islamic Republic Of", code: "IR", phoneCode: "+98", phoneNumberLength: 10 },
  { name: "Iraq", code: "IQ", phoneCode: "+964", phoneNumberLength: 10 },
  { name: "Ireland", code: "IE", phoneCode: "+353", phoneNumberLength: 9 },
  { name: "Isle of Man", code: "IM", phoneCode: "+44", phoneNumberLength: 10 },
  { name: "Israel", code: "IL", phoneCode: "+972", phoneNumberLength: 9 },
  { name: "Italy", code: "IT", phoneCode: "+39", phoneNumberLength: 10 },
  { name: "Jamaica", code: "JM", phoneCode: "+1-876", phoneNumberLength: 7 },
  { name: "Japan", code: "JP", phoneCode: "+81", phoneNumberLength: 10 },
  { name: "Jersey", code: "JE", phoneCode: "+44", phoneNumberLength: 10 },
  { name: "Jordan", code: "JO", phoneCode: "+962", phoneNumberLength: 9 },
  { name: "Kazakhstan", code: "KZ", phoneCode: "+7", phoneNumberLength: 10 },
  { name: "Kenya", code: "KE", phoneCode: "+254", phoneNumberLength: 9 },
  { name: "Kiribati", code: "KI", phoneCode: "+686", phoneNumberLength: 5 },
  { name: "Korea, Democratic People'S Republic of", code: "KP", phoneCode: "+850", phoneNumberLength: 8 },
  { name: "Korea, Republic of", code: "KR", phoneCode: "+82", phoneNumberLength: 10 },
  { name: "Kuwait", code: "KW", phoneCode: "+965", phoneNumberLength: 8 },
  { name: "Kyrgyzstan", code: "KG", phoneCode: "+996", phoneNumberLength: 9 },
  { name: "Lao People'S Democratic Republic", code: "LA", phoneCode: "+856", phoneNumberLength: 8 },
  { name: "Latvia", code: "LV", phoneCode: "+371", phoneNumberLength: 8 },
  { name: "Lebanon", code: "LB", phoneCode: "+961", phoneNumberLength: 8 },
  { name: "Lesotho", code: "LS", phoneCode: "+266", phoneNumberLength: 8 },
  { name: "Liberia", code: "LR", phoneCode: "+231", phoneNumberLength: 7 },
  { name: "Libyan Arab Jamahiriya", code: "LY", phoneCode: "+218", phoneNumberLength: 9 },
  { name: "Liechtenstein", code: "LI", phoneCode: "+423", phoneNumberLength: 7 },
  { name: "Lithuania", code: "LT", phoneCode: "+370", phoneNumberLength: 8 },
  { name: "Luxembourg", code: "LU", phoneCode: "+352", phoneNumberLength: 9 },
  { name: "Macao", code: "MO", phoneCode: "+853", phoneNumberLength: 8 },
  { name: "Macedonia, The Former Yugoslav Republic of", code: "MK", phoneCode: "+389", phoneNumberLength: 8 },
  { name: "Madagascar", code: "MG", phoneCode: "+261", phoneNumberLength: 9 },
  { name: "Malawi", code: "MW", phoneCode: "+265", phoneNumberLength: 9 },
  { name: "Malaysia", code: "MY", phoneCode: "+60", phoneNumberLength: 9 },
  { name: "Maldives", code: "MV", phoneCode: "+960", phoneNumberLength: 7 },
  { name: "Mali", code: "ML", phoneCode: "+223", phoneNumberLength: 8 },
  { name: "Malta", code: "MT", phoneCode: "+356", phoneNumberLength: 8 },
  { name: "Marshall Islands", code: "MH", phoneCode: "+692", phoneNumberLength: 7 },
  { name: "Martinique", code: "MQ", phoneCode: "+596", phoneNumberLength: 9 },
  { name: "Mauritania", code: "MR", phoneCode: "+222", phoneNumberLength: 8 },
  { name: "Mauritius", code: "MU", phoneCode: "+230", phoneNumberLength: 8 },
  { name: "Mayotte", code: "YT", phoneCode: "+262", phoneNumberLength: 9 },
  { name: "Mexico", code: "MX", phoneCode: "+52", phoneNumberLength: 10 },
  { name: "Micronesia, Federated States of", code: "FM", phoneCode: "+691", phoneNumberLength: 7 },
  { name: "Moldova, Republic of", code: "MD", phoneCode: "+373", phoneNumberLength: 8 },
  { name: "Monaco", code: "MC", phoneCode: "+377", phoneNumberLength: 8 },
  { name: "Mongolia", code: "MN", phoneCode: "+976", phoneNumberLength: 8 },
  { name: "Montserrat", code: "MS", phoneCode: "+1-664", phoneNumberLength: 7 },
  { name: "Morocco", code: "MA", phoneCode: "+212", phoneNumberLength: 9 },
  { name: "Mozambique", code: "MZ", phoneCode: "+258", phoneNumberLength: 9 },
  { name: "Myanmar", code: "MM", phoneCode: "+95", phoneNumberLength: 9 },
  { name: "Namibia", code: "NA", phoneCode: "+264", phoneNumberLength: 8 },
  { name: "Nauru", code: "NR", phoneCode: "+674", phoneNumberLength: 7 },
  { name: "Nepal", code: "NP", phoneCode: "+977", phoneNumberLength: 10 },
  { name: "Netherlands", code: "NL", phoneCode: "+31", phoneNumberLength: 9 },
  { name: "Netherlands Antilles", code: "AN", phoneCode: "+599", phoneNumberLength: 7 },
  { name: "New Caledonia", code: "NC", phoneCode: "+687", phoneNumberLength: 6 },
  { name: "New Zealand", code: "NZ", phoneCode: "+64", phoneNumberLength: 9 },
  { name: "Nicaragua", code: "NI", phoneCode: "+505", phoneNumberLength: 8 },
  { name: "Niger", code: "NE", phoneCode: "+227", phoneNumberLength: 8 },
  { name: "Nigeria", code: "NG", phoneCode: "+234", phoneNumberLength: 10 },
  { name: "Niue", code: "NU", phoneCode: "+683", phoneNumberLength: 4 },
  { name: "Norfolk Island", code: "NF", phoneCode: "+672", phoneNumberLength: 5 },
  { name: "Northern Mariana Islands", code: "MP", phoneCode: "+1-670", phoneNumberLength: 7 },
  { name: "Norway", code: "NO", phoneCode: "+47", phoneNumberLength: 8 },
  { name: "Oman", code: "OM", phoneCode: "+968", phoneNumberLength: 8 },
  { name: "Pakistan", code: "PK", phoneCode: "+92", phoneNumberLength: 10 },
  { name: "Palau", code: "PW", phoneCode: "+680", phoneNumberLength: 7 },
  { name: "Palestinian Territory, Occupied", code: "PS", phoneCode: "+970", phoneNumberLength: 9 },
  { name: "Panama", code: "PA", phoneCode: "+507", phoneNumberLength: 8 },
  { name: "Papua New Guinea", code: "PG", phoneCode: "+675", phoneNumberLength: 7 },
  { name: "Paraguay", code: "PY", phoneCode: "+595", phoneNumberLength: 9 },
  { name: "Peru", code: "PE", phoneCode: "+51", phoneNumberLength: 9 },
  { name: "Philippines", code: "PH", phoneCode: "+63", phoneNumberLength: 10 },
  { name: "Pitcairn", code: "PN", phoneCode: "+64", phoneNumberLength: 4 },
  { name: "Poland", code: "PL", phoneCode: "+48", phoneNumberLength: 9 },
  { name: "Portugal", code: "PT", phoneCode: "+351", phoneNumberLength: 9 },
  { name: "Puerto Rico", code: "PR", phoneCode: "+1-787", phoneNumberLength: 10 },
  { name: "Qatar", code: "QA", phoneCode: "+974", phoneNumberLength: 8 },
  { name: "Reunion", code: "RE", phoneCode: "+262", phoneNumberLength: 9 },
  { name: "Romania", code: "RO", phoneCode: "+40", phoneNumberLength: 9 },
  { name: "Russian Federation", code: "RU", phoneCode: "+7", phoneNumberLength: 10 },
  { name: "RWANDA", code: "RW", phoneCode: "+250", phoneNumberLength: 9 },
  { name: "Saint Helena", code: "SH", phoneCode: "+290", phoneNumberLength: 4 },
  { name: "Saint Kitts and Nevis", code: "KN", phoneCode: "+1-869", phoneNumberLength: 7 },
  { name: "Saint Lucia", code: "LC", phoneCode: "+1-758", phoneNumberLength: 7 },
  { name: "Saint Pierre and Miquelon", code: "PM", phoneCode: "+508", phoneNumberLength: 6 },
  { name: "Saint Vincent and the Grenadines", code: "VC", phoneCode: "+1-784", phoneNumberLength: 7 },
  { name: "Samoa", code: "WS", phoneCode: "+685", phoneNumberLength: 7 },
  { name: "San Marino", code: "SM", phoneCode: "+378", phoneNumberLength: 9 },
  { name: "Sao Tome and Principe", code: "ST", phoneCode: "+239", phoneNumberLength: 7 },
  { name: "Saudi Arabia", code: "SA", phoneCode: "+966", phoneNumberLength: 9 },
  { name: "Senegal", code: "SN", phoneCode: "+221", phoneNumberLength: 9 },
  { name: "Serbia and Montenegro", code: "CS", phoneCode: "+381", phoneNumberLength: 8 },
  { name: "Seychelles", code: "SC", phoneCode: "+248", phoneNumberLength: 7 },
  { name: "Sierra Leone", code: "SL", phoneCode: "+232", phoneNumberLength: 8 },
  { name: "Singapore", code: "SG", phoneCode: "+65", phoneNumberLength: 8 },
  { name: "Slovakia", code: "SK", phoneCode: "+421", phoneNumberLength: 9 },
  { name: "Slovenia", code: "SI", phoneCode: "+386", phoneNumberLength: 8 },
  { name: "Solomon Islands", code: "SB", phoneCode: "+677", phoneNumberLength: 7 },
  { name: "Somalia", code: "SO", phoneCode: "+252", phoneNumberLength: 8 },
  { name: "South Africa", code: "ZA", phoneCode: "+27", phoneNumberLength: 9 },
  { name: "South Georgia and the South Sandwich Islands", code: "GS", phoneCode: "+500", phoneNumberLength: 5 },
  { name: "Spain", code: "ES", phoneCode: "+34", phoneNumberLength: 9 },
  { name: "Sri Lanka", code: "LK", phoneCode: "+94", phoneNumberLength: 9 },
  { name: "Sudan", code: "SD", phoneCode: "+249", phoneNumberLength: 9 },
  { name: "Suriname", code: "SR", phoneCode: "+597", phoneNumberLength: 7 },
  { name: "Svalbard and Jan Mayen", code: "SJ", phoneCode: "+47", phoneNumberLength: 8 },
  { name: "Swaziland", code: "SZ", phoneCode: "+268", phoneNumberLength: 8 },
  { name: "Sweden", code: "SE", phoneCode: "+46", phoneNumberLength: 9 },
  { name: "Switzerland", code: "CH", phoneCode: "+41", phoneNumberLength: 9 },
  { name: "Syrian Arab Republic", code: "SY", phoneCode: "+963", phoneNumberLength: 9 },
  { name: "Taiwan, Province of China", code: "TW", phoneCode: "+886", phoneNumberLength: 9 },
  { name: "Tajikistan", code: "TJ", phoneCode: "+992", phoneNumberLength: 9 },
  { name: "Tanzania, United Republic of", code: "TZ", phoneCode: "+255", phoneNumberLength: 9 },
  { name: "Thailand", code: "TH", phoneCode: "+66", phoneNumberLength: 9 },
  { name: "Timor-Leste", code: "TL", phoneCode: "+670", phoneNumberLength: 7 },
  { name: "Togo", code: "TG", phoneCode: "+228", phoneNumberLength: 8 },
  { name: "Tokelau", code: "TK", phoneCode: "+690", phoneNumberLength: 4 },
  { name: "Tonga", code: "TO", phoneCode: "+676", phoneNumberLength: 5 },
  { name: "Trinidad and Tobago", code: "TT", phoneCode: "+1-868", phoneNumberLength: 7 },
  { name: "Tunisia", code: "TN", phoneCode: "+216", phoneNumberLength: 8 },
  { name: "Turkey", code: "TR", phoneCode: "+90", phoneNumberLength: 10 },
  { name: "Turkmenistan", code: "TM", phoneCode: "+993", phoneNumberLength: 8 },
  { name: "Turks and Caicos Islands", code: "TC", phoneCode: "+1-649", phoneNumberLength: 7 },
  { name: "Tuvalu", code: "TV", phoneCode: "+688", phoneNumberLength: 5 },
  { name: "Uganda", code: "UG", phoneCode: "+256", phoneNumberLength: 9 },
  { name: "Ukraine", code: "UA", phoneCode: "+380", phoneNumberLength: 9 },
  { name: "United Arab Emirates", code: "AE", phoneCode: "+971", phoneNumberLength: 9 },
  { name: "United Kingdom", code: "GB", phoneCode: "+44", phoneNumberLength: 10 },
  { name: "United States", code: "US", phoneCode: "+1", phoneNumberLength: 10 },
  { name: "United States Minor Outlying Islands", code: "UM", phoneCode: "+1", phoneNumberLength: 10 },
  { name: "Uruguay", code: "UY", phoneCode: "+598", phoneNumberLength: 8 },
  { name: "Uzbekistan", code: "UZ", phoneCode: "+998", phoneNumberLength: 9 },
  { name: "Vanuatu", code: "VU", phoneCode: "+678", phoneNumberLength: 7 },
  { name: "Venezuela", code: "VE", phoneCode: "+58", phoneNumberLength: 10 },
  { name: "Viet Nam", code: "VN", phoneCode: "+84", phoneNumberLength: 9 },
  { name: "Virgin Islands, British", code: "VG", phoneCode: "+1-284", phoneNumberLength: 7 },
  { name: "Virgin Islands, U.S.", code: "VI", phoneCode: "+1-340", phoneNumberLength: 7 },
  { name: "Wallis and Futuna", code: "WF", phoneCode: "+681", phoneNumberLength: 6 },
  { name: "Western Sahara", code: "EH", phoneCode: "+212", phoneNumberLength: 9 },
  { name: "Yemen", code: "YE", phoneCode: "+967", phoneNumberLength: 9 },
  { name: "Zambia", code: "ZM", phoneCode: "+260", phoneNumberLength: 9 },
  { name: "Zimbabwe", code: "ZW", phoneCode: "+263", phoneNumberLength: 9 },
];

export const GOUVERNORATS = [
  "Ariana",
  "Beja",
  "Ben Arous",
  "Bizerte",
  "Gabes",
  "Gafsa",
  "Jendouba",
  "Kairouan",
  "Kasserine",
  "Kebili",
  "Le Kef",
  "Mahdia",
  "Mannouba",
  "Medenine",
  "Monastir",
  "Nabeul",
  "Sfax",
  "Sidi Bouzid",
  "Siliana",
  "Sousse",
  "Tataouine",
  "Tozeur",
  "Tunis",
  "Zaghouan",
];